### ISSUE TITLE
Consider rebuilding on a framework

### ISSUE THREAD

**Issue by evansharp** [mikkelsvartveit/splitlist#1]
I saw your post on Reddit. IF you wanted to take this big, which I think you could, I have a few big-picture suggestions:

To abstract your routes and database work, have a look at an ultralight framework like http://flightphp.com/ / https://github.com/mikecao/flight. 

You could branch your project where it is, put the branch on Composer, require Flight, and just port your pages as a route.

**Comment by mikkelsvartveit** [comment]
Interesting, thank you for the suggestion!
